name: Build and publish
on:
  pull_request: { }
  push:
    branches: [ master ]
jobs:
  build:
    name: "Build and publish to docker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hughns/element-web:${{ github.sha }}
